/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DivisieannotatieLinks } from './divisieannotatieLinks';
import { Registratiegegevens } from './registratiegegevens';
import { Thema } from './thema';
import { RegeltekstDocumentKruimelpadInner } from './regeltekstDocumentKruimelpadInner';
import { Embedded } from './embedded';


/**
 * Divisieannotatie kan een Divisie of een DivisieTekst zijn, zoals beschreven in CIMOW
 */
export interface Divisieannotatie { 
    identificatie: string;
    geregistreerdMet: Registratiegegevens;
    documentIdentificatie?: string;
    /**
     * Een lijst van verwijzingen naar regelteksten, oftewel artikelen en/of leden, die juridische regels bevatten over de deze activiteit. De verwijzing is in deze de identificatie van een regeltekst, in de vorm van een AKN identificatie. Het gaat om alle regels in de tijd (verleden heden, toekomst). Desgewenst kunnen tijdreisparameters aangegeven worden, om een extra filter aan te brengen.
     */
    juridischeGrondslagIdentificatie?: Array<string>;
    documentKruimelpad?: Array<RegeltekstDocumentKruimelpadInner>;
    themas?: Array<Thema>;
    _embedded?: Embedded;
    _links: DivisieannotatieLinks;
}

