/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface LocatieZoekgebiedenEmbedded { 
    locatieidentificaties?: Array<string>;
    /**
     * Als omgevingsplanPons true is, valt het zoekgebied geheel binnen één of meerdere vastgestelde ponsen. \\ De zoekgeometrie valt binnen de pons(en) als alle punten van de zoekgeometrie een intersectie hebben \\  met het binnenste of de rand van de pons(en), i.e. covers uit het DE-9IM. 
     */
    omgevingsplanPons: boolean;
}

