/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Kaartextent } from './kaartextent';
import { OntwerpRegistratiegegevens } from './ontwerpRegistratiegegevens';
import { SelfLinks } from './selfLinks';
import { OntwerpKaartlaag } from './ontwerpKaartlaag';


export interface OntwerpKaart { 
    identificatie: string;
    ontwerpbesluitIdentificatie: string;
    /**
     * Een technische identificatie voor ontwerpobjecten, samengesteld uit de IMOW-identificatie en de ontwerpbesluitIdentificatie, die gebruikt kan worden als pad parameter en in zoekopdrachten.
     */
    technischId: string;
    naam: string;
    nummer?: string;
    uitsnede: Kaartextent;
    bevat: Array<OntwerpKaartlaag>;
    /**
     * Met deze status kan aangegeven aangegeven dat een OW-object beëindigd moet worden.
     */
    status?: string;
    geregistreerdMet: OntwerpRegistratiegegevens;
    _links: SelfLinks;
}

