/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Zoekobject om te zoeken met een parameter.
 */
export interface OntwerpDocumentregeltekstZoekParameter { 
    parameter?: OntwerpDocumentregeltekstZoekParameter.ParameterEnum;
    /**
     * Waarden waarop gezocht moet worden voor de betreffende parameter
     */
    zoekWaarden?: Array<string>;
}
export namespace OntwerpDocumentregeltekstZoekParameter {
    export type ParameterEnum = 'activiteit.identificatie' | 'gebiedsaanwijzing.identificatie' | 'locatie.identificatie' | 'ontwerplocatie.technischId' | 'omgevingsnorm.identificatie' | 'omgevingswaarde.identificatie' | 'thema.code' | 'ontwerpregeltekst.type' | 'document.type' | 'document.bevoegdGezag' | 'document.typeBevoegdGezag' | 'instructieregelInstrument' | 'instructieregelTaakuitoefening';
    export const ParameterEnum = {
        ActiviteitIdentificatie: 'activiteit.identificatie' as ParameterEnum,
        GebiedsaanwijzingIdentificatie: 'gebiedsaanwijzing.identificatie' as ParameterEnum,
        LocatieIdentificatie: 'locatie.identificatie' as ParameterEnum,
        OntwerplocatieTechnischId: 'ontwerplocatie.technischId' as ParameterEnum,
        OmgevingsnormIdentificatie: 'omgevingsnorm.identificatie' as ParameterEnum,
        OmgevingswaardeIdentificatie: 'omgevingswaarde.identificatie' as ParameterEnum,
        ThemaCode: 'thema.code' as ParameterEnum,
        OntwerpregeltekstType: 'ontwerpregeltekst.type' as ParameterEnum,
        DocumentType: 'document.type' as ParameterEnum,
        DocumentBevoegdGezag: 'document.bevoegdGezag' as ParameterEnum,
        DocumentTypeBevoegdGezag: 'document.typeBevoegdGezag' as ParameterEnum,
        InstructieregelInstrument: 'instructieregelInstrument' as ParameterEnum,
        InstructieregelTaakuitoefening: 'instructieregelTaakuitoefening' as ParameterEnum
    };
}


