/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocumentComponent } from './documentComponent';
import { Adressaat } from './adressaat';
import { Regeltekst } from './regeltekst';
import { Thema } from './thema';
import { TypeJuridischeRegels } from './typeJuridischeRegels';
import { RegeltekstDocumentKruimelpadInner } from './regeltekstDocumentKruimelpadInner';
import { Instrument } from './instrument';
import { OntwerpRegeltekstLinks } from './ontwerpRegeltekstLinks';
import { Embedded1 } from './embedded1';
import { OntwerpRegistratiegegevens } from './ontwerpRegistratiegegevens';


/**
 * Een Regeltekst is de kleinste zelfstandige eenheid van (een of meer) bij elkaar behorende juridische regels. Deze regels horen onlosmakelijk bij elkaar en hebben gezamenlijk één werkingsgebied.
 */
export interface OntwerpRegeltekst { 
    ontwerpbesluitIdentificatie?: string;
    /**
     * TechnischId beschrijving
     */
    technischId?: string;
    identificatie: string;
    /**
     * De letterlijke tekst waarmee de Regeltekst is omschreven, in een artikel of een lid. Een Regeltekst is altijd één doorlopend stuk juridische tekst, welke juridische regels bevat.
     */
    omschrijving: string;
    thema?: Array<Thema>;
    /**
     * Een lijst van verwijzingen naar regelteksten, oftewel artikelen en/of leden, die juridische regels bevatten over de deze activiteit. De verwijzing is in deze de identificatie van een regeltekst, in de vorm van een AKN identificatie. Het gaat om alle regels in de tijd (verleden heden, toekomst). Desgewenst kunnen tijdreisparameters aangegeven worden, om een extra filter aan te brengen.
     */
    juridischeGrondslagIdentificatie?: Array<string>;
    typeJuridischeRegels?: TypeJuridischeRegels;
    instructieregelInstrument?: Array<Instrument>;
    instructieregelTaakuitoefening?: Array<Adressaat>;
    isRegelstructuurannotatieBij: DocumentComponent;
    documentKruimelpad?: Array<RegeltekstDocumentKruimelpadInner>;
    _embedded?: Embedded1;
    /**
     * Verwijzing dat aangeeft dat er een bijzondere relatie bestaat tussen twee Regelteksten.
     */
    gerelateerd?: Array<OntwerpRegeltekst>;
    /**
     * Verwijzing dat aangeeft dat er een bijzondere relatie bestaat tussen twee Regelteksten.
     */
    gerelateerdVastgesteld?: Array<Regeltekst>;
    /**
     * Met deze status kan aangegeven aangegeven dat een OW-object beëindigd moet worden.
     */
    status?: string;
    geregistreerdMet: OntwerpRegistratiegegevens;
    _links: OntwerpRegeltekstLinks;
    documentTechnischId?: string;
}

