/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Een enkele suggestie
 */
export interface OntwerpRegelingSuggestie { 
    /**
     * De titel van de OntwerpRegeling zoals deze wordt gebruikt in aanhalingen.
     */
    citeerTitel?: string;
    /**
     * Een technische identificatie voor ontwerpobjecten, samengesteld uit de IMOW-identificatie en de ontwerpbesluitIdentificatie, die gebruikt kan worden als pad parameter en in zoekopdrachten.
     */
    technischId?: string;
    /**
     * De identificatie waaronder elk object van dit type bekend is.
     */
    identificatie?: string;
    /**
     * Het bevoegd gezag dat een bepaald omgevingsdocument aanlevert.
     */
    bevoegdGezag?: string;
    /**
     * Het type Regeling dat aangeleverd wordt.
     */
    type?: string;
    /**
     * Moment vanaf wanneer deze versie bekend is bij Ozon. Deze versie is actief totdat er een nieuwe versie beschikbaar komt. Datumtijd in ISO 8601 formaat.
     */
    tijdstipRegistratie?: string;
    /**
     * Moment vanaf wanneer er een nieuwere versie dan deze versie bekend is bij Ozon. Deze versie is vanaf dit moment niet meer actief. Datumtijd in ISO 8601 formaat.
     */
    eindRegistratie?: string;
}

