/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Zoekobject om te zoeken met een parameter.
 */
export interface OntwerpDocumentvrijetekstZoekParameter { 
    parameter?: OntwerpDocumentvrijetekstZoekParameter.ParameterEnum;
    /**
     * Waarden waarop gezocht moet worden voor de betreffende parameter
     */
    zoekWaarden?: Array<string>;
}
export namespace OntwerpDocumentvrijetekstZoekParameter {
    export type ParameterEnum = 'gebiedsaanwijzing.identificatie' | 'locatie.identificatie' | 'hoofdlijn.identificatie' | 'thema.code' | 'document.type' | 'ontwerpdocument.technischId' | 'ontwerpgebiedsaanwijzing.technischId' | 'ontwerplocatie.technischId' | 'ontwerphoofdlijn.technischId' | 'document.typeBevoegdGezag' | 'document.bevoegdGezag';
    export const ParameterEnum = {
        GebiedsaanwijzingIdentificatie: 'gebiedsaanwijzing.identificatie' as ParameterEnum,
        LocatieIdentificatie: 'locatie.identificatie' as ParameterEnum,
        HoofdlijnIdentificatie: 'hoofdlijn.identificatie' as ParameterEnum,
        ThemaCode: 'thema.code' as ParameterEnum,
        DocumentType: 'document.type' as ParameterEnum,
        OntwerpdocumentTechnischId: 'ontwerpdocument.technischId' as ParameterEnum,
        OntwerpgebiedsaanwijzingTechnischId: 'ontwerpgebiedsaanwijzing.technischId' as ParameterEnum,
        OntwerplocatieTechnischId: 'ontwerplocatie.technischId' as ParameterEnum,
        OntwerphoofdlijnTechnischId: 'ontwerphoofdlijn.technischId' as ParameterEnum,
        DocumentTypeBevoegdGezag: 'document.typeBevoegdGezag' as ParameterEnum,
        DocumentBevoegdGezag: 'document.bevoegdGezag' as ParameterEnum
    };
}


