/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Standaardformaat (`application/problem+json`) voor probleemdetails in HTTP API\'s (RFC 7807).
 */
export interface Problem404 { 
    /**
     * Absolute URI dat het probleemtype identificeert. 
     */
    type?: string;
    /**
     * Een korte samenvatting van het probleemtype bedoeld voor ontwikkelaars. 
     */
    title?: string;
    /**
     * De HTTP statuscode gegenereerd door de server waar het probleem zich voordoet. 
     */
    status?: number;
    /**
     * Mens-leesbare uitleg van dit specifieke probleem. 
     */
    detail?: string;
    /**
     * Absolute URI dat dit specifieke probleem identificeert. 
     */
    instance?: string;
}

