/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SoortRegeling } from './soortRegeling';
import { RegelingLinks } from './regelingLinks';
import { Registratiegegevens } from './registratiegegevens';
import { Locatie } from './locatie';
import { BevoegdGezag } from './bevoegdGezag';


/**
 * Een tekst (met eventuele afbeeldingen en andere multimedia-elementen) die juridische voorschriften van algemene strekking of beleidsregels bevat.
 */
export interface Regeling { 
    heeftTijdelijkDeel?: Array<Regeling>;
    identificatie: string;
    officieleTitel: string;
    aangeleverdDoorEen: BevoegdGezag;
    _links: RegelingLinks;
    type: SoortRegeling;
    geregistreerdMet: Registratiegegevens;
    citeerTitel?: string;
    opschrift?: string;
    conditie?: string;
    opvolgerVan?: Array<Regeling>;
    heeftRegelingsgebied: Locatie;
    heeftBijlagen?: boolean;
    heeftToelichtingen?: boolean;
    publicatieID?: string;
    inwerkingTot?: string;
    geldigTot?: string;
}

