/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * Één van de kwantitatieve of kwalitatieve waarden van een norm. De normwaarde geeft aan wat de specifieke kwantitatieve of kwalitatieve eisen zijn, inclusief de toewijzing ervan aan de specifieke locatie(s) waar de normwaarde voor geldt. 
 */
export interface Registratiegegevens { 
    versie?: number;
    beginInwerking: string;
    beginGeldigheid: string;
    eindGeldigheid?: string;
    /**
     * Moment vanaf wanneer deze versie bekend is bij Ozon. Deze versie is actief totdat er een nieuwe versie beschikbaar komt. Datumtijd in ISO 8601 formaat.
     */
    tijdstipRegistratie: string;
    /**
     * Moment vanaf wanneer er een nieuwere versie dan deze versie bekend is bij Ozon. Deze versie is vanaf dit moment niet meer actief. Datumtijd in ISO 8601 formaat.
     */
    eindRegistratie?: string;
    /**
     * De status van een object is een aanduiding waarmee aangegeven kan worden dat de OW-informatie, in deze versie van het object, niet meer geldig is. Dit geeft bijvoorbeeld aan of deze activiteit beeindigd (\'B\') is.
     */
    status?: Registratiegegevens.StatusEnum;
}
export namespace Registratiegegevens {
    export type StatusEnum = 'B' | 'null';
    export const StatusEnum = {
        B: 'B' as StatusEnum,
        Null: 'null' as StatusEnum
    };
}


