/**
 * Omgevingsdocumenten-Presenteren
 * De Omgevingsdocumenten Presenteren API ontsluit beschikbaar gestelde omgevingsdocumenten op zo\'n manier dat deze eenvoudig visueel te verbeelden zijn. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/> De Omgevingsdocumenten Presenteren API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks.
 *
 * The version of the OpenAPI document: 7.5.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Hoofdlijn } from './hoofdlijn';
import { Kaart } from './kaart';
import { Thema } from './thema';
import { Gebiedsaanwijzing } from './gebiedsaanwijzing';
import { Idealisatie } from './idealisatie';
import { Locatie } from './locatie';
import { SelfLinks } from './selfLinks';
import { Divisieannotatie } from './divisieannotatie';


/**
 * Tekstdeel is de kleinste zelfstandige eenheid van (een of meer) bij elkaar horende Juridische teksten in een tekst met Vrijetekststructuur, te weten een FormeleInhoud.
 */
export interface Tekstdeel { 
    identificatie: string;
    idealisatie?: Idealisatie;
    omschrijving: string;
    thema?: Array<Thema>;
    bevat?: Array<Hoofdlijn>;
    divisieannotatieverwijzing?: Array<Divisieannotatie>;
    wijstGebiedAan?: Array<Gebiedsaanwijzing>;
    benoemt?: Array<Kaart>;
    definieert?: Array<Locatie>;
    _links: SelfLinks;
}

