/**
 * Strip properties generated by OpenLayers that gets generated newly on each call and interfere
 * with equality checks.
 * The objects are not typed as OL types do not include these properties
 * @warn Use only for tests
 * @param input Any OpenLayer object
 * @returns nothing, the object is changed in-memory
 */
export function stripOl(input: unknown): void {
  if (input == null) {
    return;
  }
  /* eslint-disable @typescript-eslint/no-explicit-any */
  delete (input as any).ol_uid;
  delete (input as any).simplifyTransformedInternal;
  delete (input as any).listeners_;
  /* eslint-enable @typescript-eslint/no-explicit-any */
}
