/**
 * Omgevingsdocumenten-Verbeelden-v3
 * De Omgevingsdocumenten Verbeelden API ontsluit informatie tbv het verbeelden van beschikbaar gestelde omgevingsdocumenten. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/>  De Omgevingsdocumenten Verbeelden API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks. Layers zijn gebaseerd op de <a href=\"https://docs.ogc.org/DRAFTS/20-057.html\">OGC API Tiles</a>.
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PrimairObjectIdentificator } from './primairObjectIdentificator';


/**
 * Generiek zoekobject voor mapbox bevragingen voor objecten.
 */
export interface GeneriekZoekobject { 
    objectType: GeneriekZoekobject.ObjectTypeEnum;
    primairObjectIdentificator: PrimairObjectIdentificator;
    /**
     * Een lijst identificaties van het bij het objecttype ondergelegen objecten, verplicht m.u.v. gebiedsaanwijzingen. Voor het WerkingsgebiedZoekobject en OntwerpWerkingsgebiedZoekobject zijn SecundaireIdentificatoren optioneel in te vullen met werkingsgebied identificaties en/of technischId voor het verbeelden van specifieke werkingsgebieden.
     */
    secundaireObjectIdentificatoren?: Array<string>;
}
export namespace GeneriekZoekobject {
    export type ObjectTypeEnum = 'GebiedsaanwijzingZoekobject' | 'OmgevingsnormNormwaardeZoekobject' | 'OmgevingswaardeNormwaardeZoekobject' | 'RegeltekstActiviteitlocatieaanduidingZoekobject' | 'KaartKaartlaagZoekobject' | 'WerkingsgebiedZoekobject' | 'RegelingsgebiedZoekobject' | 'OntwerpGebiedsaanwijzingZoekobject' | 'OntwerpOmgevingsnormNormwaardeZoekobject' | 'OntwerpOmgevingswaardeNormwaardeZoekobject' | 'OntwerpRegeltekstActiviteitlocatieaanduidingZoekobject' | 'OntwerpKaartKaartlaagZoekobject' | 'OntwerpWerkingsgebiedZoekobject' | 'OntwerpRegelingsgebiedZoekobject';
    export const ObjectTypeEnum = {
        GebiedsaanwijzingZoekobject: 'GebiedsaanwijzingZoekobject' as ObjectTypeEnum,
        OmgevingsnormNormwaardeZoekobject: 'OmgevingsnormNormwaardeZoekobject' as ObjectTypeEnum,
        OmgevingswaardeNormwaardeZoekobject: 'OmgevingswaardeNormwaardeZoekobject' as ObjectTypeEnum,
        RegeltekstActiviteitlocatieaanduidingZoekobject: 'RegeltekstActiviteitlocatieaanduidingZoekobject' as ObjectTypeEnum,
        KaartKaartlaagZoekobject: 'KaartKaartlaagZoekobject' as ObjectTypeEnum,
        WerkingsgebiedZoekobject: 'WerkingsgebiedZoekobject' as ObjectTypeEnum,
        RegelingsgebiedZoekobject: 'RegelingsgebiedZoekobject' as ObjectTypeEnum,
        OntwerpGebiedsaanwijzingZoekobject: 'OntwerpGebiedsaanwijzingZoekobject' as ObjectTypeEnum,
        OntwerpOmgevingsnormNormwaardeZoekobject: 'OntwerpOmgevingsnormNormwaardeZoekobject' as ObjectTypeEnum,
        OntwerpOmgevingswaardeNormwaardeZoekobject: 'OntwerpOmgevingswaardeNormwaardeZoekobject' as ObjectTypeEnum,
        OntwerpRegeltekstActiviteitlocatieaanduidingZoekobject: 'OntwerpRegeltekstActiviteitlocatieaanduidingZoekobject' as ObjectTypeEnum,
        OntwerpKaartKaartlaagZoekobject: 'OntwerpKaartKaartlaagZoekobject' as ObjectTypeEnum,
        OntwerpWerkingsgebiedZoekobject: 'OntwerpWerkingsgebiedZoekobject' as ObjectTypeEnum,
        OntwerpRegelingsgebiedZoekobject: 'OntwerpRegelingsgebiedZoekobject' as ObjectTypeEnum
    };
}


