/**
 * Omgevingsdocumenten-Verbeelden-v3
 * De Omgevingsdocumenten Verbeelden API ontsluit informatie tbv het verbeelden van beschikbaar gestelde omgevingsdocumenten. Op de Ontwikkel, Test, Acceptatie en Pre-productieomgeving worden ook omgevingsdocumenten toegevoegd en verwijderd door beheerders voor testdoeleinden binnen en buiten de voorziening.<br/> <br/>  De Omgevingsdocumenten Verbeelden API volgt de standaarden zoals beschreven in de DSO API-strategie versie 1.1. Zo is het standaard mediatype HAL (`application/hal+json`). Dit is een mediatype voor het weergeven van resources en hun relaties via hyperlinks. Layers zijn gebaseerd op de <a href=\"https://docs.ogc.org/DRAFTS/20-057.html\">OGC API Tiles</a>.
 *
 * The version of the OpenAPI document: 3.2.2
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MapboxStyleRequestItem } from './mapboxStyleRequestItem';


export interface MapboxStyleRequest { 
    symboollocaties?: Array<MapboxStyleRequestItem>;
}

